"""
Atlas Memory Models
-------------------
Pydantic models for all memory types: episodic, factual, procedural, and conversation.
These models define the structure for storing and retrieving different kinds of memories.

Memory Types:
- Episodic: Past events, interactions, tool calls (semantic search enabled)
- Factual: Structured facts (contacts, projects, preferences)
- Procedural: Skills and workflow definitions
- Conversation: Chat history for session context
"""

from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
import uuid


# ─── EPISODIC MEMORY ──────────────────────────────────────────────────────────
# Events and interactions. Stored with embeddings for semantic search.

class EpisodicMemory(BaseModel):
    """A single episodic memory: past event, interaction, or tool call result."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: int
    
    # What happened
    event_type: str  # e.g. "tool_execution", "email_received", "calendar_event", "payment"
    summary: str  # Brief description for embedding: "Sent email to Dana about project"
    full_context: str  # Complete details for retrieval
    
    # When
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    # For retrieval
    tags: List[str] = []  # ["Dana", "invoice", "email"]
    embedding_vector: Optional[List[float]] = None  # Generated by sentence-transformers
    
    # Metadata
    source: str  # "gmail", "calendar", "paystack", "tool_call"
    reference_id: Optional[str] = None  # Gmail ID, event ID, etc.
    confidence: float = 1.0  # How certain is this memory (0-1)
    
    # Lifecycle
    ttl_days: int = 90  # Auto-expire after 90 days
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    def is_expired(self) -> bool:
        """Check if memory has exceeded TTL."""
        expiry = self.created_at + timedelta(days=self.ttl_days)
        return datetime.utcnow() > expiry


class ToolCallMemory(EpisodicMemory):
    """Specialized episodic memory for tool executions."""
    
    tool_name: str  # "send_email", "get_balance", etc.
    tool_input: Dict[str, Any]  # Input parameters
    tool_output: str  # Result (truncated if large)
    execution_time_ms: int  # How long it took
    
    def __init__(self, **data):
        super().__init__(**data)
        self.event_type = "tool_execution"
        self.source = "tool_call"


class PaymentMemory(EpisodicMemory):
    """Specialized episodic memory for payment events."""
    
    amount: float
    currency: str = "NGN"
    customer_email: str
    reference: str
    transaction_type: str  # "charge", "transfer", "refund"
    
    def __init__(self, **data):
        super().__init__(**data)
        self.event_type = "payment"
        self.source = "paystack"


# ─── FACTUAL MEMORY ───────────────────────────────────────────────────────────
# Structured facts that don't change frequently.

class FactualMemory(BaseModel):
    """A structured fact: contact info, project details, user preference."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: int
    
    # Fact key and value
    key: str  # "contact:Dana", "project:FundMatch", "preference:timezone"
    category: str  # "contact", "project", "preference", "account"
    value: Dict[str, Any]  # Flexible structure: {"email": "...", "phone": "..."}
    
    # Metadata
    source: str  # Where this fact came from
    verified: bool = False  # Was this fact verified by the user?
    
    # Lifecycle
    last_updated: datetime = Field(default_factory=datetime.utcnow)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        arbitrary_types_allowed = True


class ContactMemory(FactualMemory):
    """Specialized factual memory for contacts."""
    
    name: str
    email: Optional[str] = None
    phone: Optional[str] = None
    timezone: Optional[str] = None
    communication_preference: Optional[str] = None  # "email", "whatsapp", "telegram"
    tags: List[str] = []  # ["client", "vendor", "friend"]
    
    def __init__(self, **data):
        super().__init__(**data)
        self.category = "contact"


class ProjectMemory(FactualMemory):
    """Specialized factual memory for projects."""
    
    name: str
    description: str
    status: str  # "active", "completed", "paused"
    client: Optional[str] = None
    start_date: Optional[datetime] = None
    deadline: Optional[datetime] = None
    
    def __init__(self, **data):
        super().__init__(**data)
        self.category = "project"


class PreferenceMemory(FactualMemory):
    """Specialized factual memory for user preferences."""
    
    setting_name: str
    setting_value: Any
    applies_to: str  # "global", "communication", "scheduling", "notifications"
    
    def __init__(self, **data):
        super().__init__(**data)
        self.category = "preference"


# ─── PROCEDURAL MEMORY ────────────────────────────────────────────────────────
# Skills and workflows (YAML-based).

class ProceduralMemory(BaseModel):
    """A skill or workflow definition."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: int
    
    # Skill details
    skill_name: str  # "morning_briefing", "invoice_and_email"
    skill_definition: str  # YAML definition (stored as string)
    description: Optional[str] = None
    
    # Metadata
    tags: List[str] = []  # ["scheduling", "email", "finance"]
    usage_count: int = 0  # How many times has this been used?
    
    # Lifecycle
    created_at: datetime = Field(default_factory=datetime.utcnow)
    last_used: Optional[datetime] = None
    
    class Config:
        arbitrary_types_allowed = True


# ─── CONVERSATION MEMORY ──────────────────────────────────────────────────────
# Short-term session context.

class ConversationTurn(BaseModel):
    """A single turn in a conversation (user message + assistant response)."""
    
    turn_number: int
    user_message: str
    assistant_response: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    # For semantic search
    user_embedding: Optional[List[float]] = None
    assistant_embedding: Optional[List[float]] = None
    
    # Metadata
    tool_calls: List[str] = []  # Tools used in this turn


class ConversationMemory(BaseModel):
    """Complete conversation session."""
    
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    user_id: int
    session_id: str  # Telegram chat ID or session identifier
    
    # Turns
    turns: List[ConversationTurn] = []
    
    # Metadata
    started_at: datetime = Field(default_factory=datetime.utcnow)
    last_turn_at: datetime = Field(default_factory=datetime.utcnow)
    
    # Session lifecycle
    ttl_hours: int = 48  # Keep in memory for 48 hours after last turn
    
    def is_expired(self) -> bool:
        """Check if conversation session has expired."""
        expiry = self.last_turn_at + timedelta(hours=self.ttl_hours)
        return datetime.utcnow() > expiry
    
    def add_turn(self, user_msg: str, assistant_resp: str, tools_used: List[str] = None):
        """Add a new turn to the conversation."""
        turn = ConversationTurn(
            turn_number=len(self.turns) + 1,
            user_message=user_msg,
            assistant_response=assistant_resp,
            tool_calls=tools_used or []
        )
        self.turns.append(turn)
        self.last_turn_at = datetime.utcnow()


# ─── MEMORY SEARCH RESULTS ────────────────────────────────────────────────────

class MemorySearchResult(BaseModel):
    """Result of a semantic memory search."""
    
    memory_type: str  # "episodic", "factual", "procedural"
    id: str
    summary: str
    relevance_score: float  # 0-1, higher = more relevant
    source: str
    timestamp: Optional[datetime] = None


class MemoryRetrievalContext(BaseModel):
    """Context to inject into LLM prompt from memory."""
    
    user_id: int
    query: str  # The query that triggered retrieval
    relevant_episodic: List[MemorySearchResult] = []  # Past events
    relevant_factual: List[MemorySearchResult] = []  # Facts/contacts/projects
    
    def format_for_prompt(self) -> str:
        """Format retrieved memories into a text block for LLM."""
        
        if not self.relevant_episodic and not self.relevant_factual:
            return ""
        
        prompt = "\n[MEMORY CONTEXT]\n"
        
        if self.relevant_episodic:
            prompt += "Past interactions:\n"
            for mem in self.relevant_episodic:
                prompt += f"- {mem.summary} (relevance: {mem.relevance_score:.1%})\n"
        
        if self.relevant_factual:
            prompt += "\nKnown facts:\n"
            for mem in self.relevant_factual:
                prompt += f"- {mem.summary}\n"
        
        prompt += "[END MEMORY CONTEXT]\n"
        return prompt
