"""
Headless OAuth helper for Atlas — works on a VPS with no browser.

Two-step flow:

  Step 1 (print URL):
      python3 scripts/generate_google_token_headless.py url

  Step 2 (consume the redirected URL Duke pastes back):
      python3 scripts/generate_google_token_headless.py finish 'http://localhost/?code=...&state=...'

Step 1 writes a tiny state file (.oauth_state.json) next to credentials.json so
Step 2 can validate the state parameter. Step 2 writes config/token.json.
"""

import json
import sys
from pathlib import Path
from urllib.parse import urlparse, parse_qs

from google_auth_oauthlib.flow import Flow

SCOPES = [
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/gmail.modify",
    "https://www.googleapis.com/auth/gmail.send",
]

REDIRECT_URI = "http://localhost"
PROJECT_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = PROJECT_DIR / "config"
CREDS_PATH = CONFIG_DIR / "credentials.json"
TOKEN_PATH = CONFIG_DIR / "token.json"
STATE_PATH = CONFIG_DIR / ".oauth_state.json"


def _build_flow() -> Flow:
    if not CREDS_PATH.exists():
        sys.exit(f"❌ {CREDS_PATH} not found.")
    flow = Flow.from_client_secrets_file(str(CREDS_PATH), SCOPES)
    flow.redirect_uri = REDIRECT_URI
    return flow


def step_url() -> None:
    flow = _build_flow()
    auth_url, state = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        prompt="consent",  # force refresh-token re-issue
    )
    # PKCE code_verifier is auto-generated by authorization_url(); persist it
    # so step_finish (a fresh Flow instance) can complete the token exchange.
    code_verifier = getattr(flow, "code_verifier", None)
    STATE_PATH.write_text(json.dumps({"state": state, "code_verifier": code_verifier}))
    print("\n--- OPEN THIS URL IN ANY BROWSER ---\n")
    print(auth_url)
    print("\nAfter you click Allow, your browser will fail to load (that's fine).")
    print("Copy the FULL URL from the address bar (starts with http://localhost/?code=...)")
    print("and pass it back to step 2:\n")
    print('   python3 scripts/generate_google_token_headless.py finish "<URL>"\n')


def step_finish(redirect_url: str) -> None:
    if not STATE_PATH.exists():
        sys.exit("❌ No saved state — run `url` step first.")
    saved = json.loads(STATE_PATH.read_text())
    saved_state = saved.get("state")
    code_verifier = saved.get("code_verifier")

    parsed = urlparse(redirect_url)
    qs = parse_qs(parsed.query)
    code = qs.get("code", [None])[0]
    incoming_state = qs.get("state", [None])[0]

    if not code:
        sys.exit("❌ No `code` parameter in the URL you pasted.")
    if saved_state and incoming_state and saved_state != incoming_state:
        sys.exit("❌ State mismatch — possible CSRF, aborting.")

    flow = _build_flow()
    if code_verifier:
        flow.code_verifier = code_verifier
    flow.fetch_token(code=code)
    TOKEN_PATH.write_text(flow.credentials.to_json())
    STATE_PATH.unlink(missing_ok=True)
    print(f"✅ token.json written to {TOKEN_PATH}")
    print("Now restart the orchestrator:")
    print("   docker compose restart orchestrator")


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in ("url", "finish"):
        sys.exit("Usage: generate_google_token_headless.py {url|finish <redirect-url>}")
    if sys.argv[1] == "url":
        step_url()
    else:
        if len(sys.argv) < 3:
            sys.exit("Usage: ... finish <redirect-url>")
        step_finish(sys.argv[2])
